import React from "react";
import { CalendarDays, CheckCircle2, Film, MapPin, Plus, Timer } from "lucide-react";
import toast from "react-hot-toast";
import { getMovies,getTheatresByLocation,createShow,getLocations } from "../../lib/api";
import Title from "../../components/Admin/Title";

export default function AddShows(){
 const [movies,setMovies]=React.useState([]),[theatres,setTheatres]=React.useState([]),[locations,setLocations]=React.useState([]);
 const [movieId,setMovieId]=React.useState(""),[theatreId,setTheatreId]=React.useState(""),[date,setDate]=React.useState(""),[time,setTime]=React.useState(""),[price,setPrice]=React.useState("");
 const [locationId,setLocationId]=React.useState("");const [saving,setSaving]=React.useState(false);
 React.useEffect(()=>{Promise.all([getMovies(),getLocations()]).then(([m,l])=>{setMovies(Array.isArray(m)?m:[]);setLocations(Array.isArray(l)?l:[])}).catch(e=>toast.error(e.message||"Unable to load data"))},[]);
 React.useEffect(()=>{if(locationId)getTheatresByLocation(locationId).then(d=>setTheatres(Array.isArray(d)?d:[])).catch(console.error);else setTheatres([]);setTheatreId("")},[locationId]);
 const submit=async(e)=>{e.preventDefault();if(!movieId||!theatreId||!date||!time||!price)return toast.error("Complete all show details");try{setSaving(true);await createShow({movieId:Number(movieId),theatreId:Number(theatreId),showDate:date,showTime:`${time}:00`,ticketPrice:Number(price)});toast.success("Show created and seats generated");setDate("");setTime("");setPrice("");}catch(e){toast.error(e.message||"Could not create show")}finally{setSaving(false)}};
 return <><Title text1="Management" text2="Add Show"/><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_330px]"><form onSubmit={submit} className="rounded-2xl border border-white/10 bg-white/[.03] p-6 sm:p-8"><div className="mb-7"><h2 className="text-xl font-semibold">Schedule a screening</h2><p className="mt-1 text-sm text-white/35">Create a show and automatically generate its seats.</p></div><div className="grid gap-5"><Field label="Movie" icon={Film}><select value={movieId} onChange={e=>setMovieId(e.target.value)}><option value="">Select movie</option>{movies.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></Field><Field label="City" icon={MapPin}><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Select city</option>{locations.map(l=><option key={l.id} value={l.id}>{l.city}</option>)}</select></Field><Field label="Theatre" icon={Film}><select value={theatreId} onChange={e=>setTheatreId(e.target.value)} disabled={!locationId}><option value="">Select theatre</option>{theatres.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><div className="grid gap-5 sm:grid-cols-3"><Field label="Date" icon={CalendarDays}><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Time" icon={Timer}><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></Field><Field label="Ticket price" icon={Plus}><input type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)} placeholder="₹ 220"/></Field></div></div><button disabled={saving} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-300 py-3.5 text-sm font-semibold text-black transition hover:bg-cyan-200 disabled:opacity-40">{saving?<><span className="h-4 w-4 animate-spin rounded-full border-2 border-black/30 border-t-black"/>Creating...</>:<><Plus size={17}/>Create show</>}</button></form><div className="rounded-2xl border border-white/10 bg-gradient-to-br from-cyan-400/10 to-white/[.02] p-6"><CheckCircle2 className="text-cyan-300"/><h3 className="mt-5 font-semibold">Automatic seat generation</h3><p className="mt-2 text-sm leading-6 text-white/40">Every new show uses the theatre capacity to generate its available seat inventory in the backend.</p></div></div></>
}
function Field({label,icon:Icon,children}){return <label className="block"><span className="mb-2 flex items-center gap-2 text-xs text-white/45"><Icon size={14} className="text-cyan-300"/>{label}</span><div className="[&_input]:h-12 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-white/10 [&_input]:bg-white/[.04] [&_input]:px-4 [&_input]:text-sm [&_input]:outline-none [&_input]:focus:border-cyan-300/40 [&_select]:h-12 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-white/10 [&_select]:bg-[#10151e] [&_select]:px-4 [&_select]:text-sm [&_select]:outline-none">{children}</div></label>}
